package com.example.hyeonsaengtime

object HyeonSaengRules {
    const val STREAK_REQUIRED_HOURS = 16

    const val ROOM_MEMBER_COUNT = 8
    const val ROOM_MAX_LEVEL = 5
    const val ROOM_XP_PER_LEVEL = 100
    const val ROOM_SUCCESS_XP = 20
    const val ROOM_MISS_XP_PENALTY = 10
    const val ROOM_ALL_MEMBER_REQUIRED_HOURS = 9
    const val ROOM_TOP_MEMBER_REQUIRED_HOURS = 18

    const val MILLIS_PER_HOUR = 60L * 60L * 1000L
    const val STREAK_REQUIRED_MILLIS = STREAK_REQUIRED_HOURS * MILLIS_PER_HOUR
    const val ROOM_TOTAL_REQUIRED_MILLIS = STREAK_REQUIRED_MILLIS * ROOM_MEMBER_COUNT
    const val ROOM_MIN_MEMBER_REQUIRED_MILLIS = STREAK_REQUIRED_MILLIS
    const val ROOM_ALL_MEMBER_REQUIRED_MILLIS = ROOM_ALL_MEMBER_REQUIRED_HOURS * MILLIS_PER_HOUR
    const val ROOM_TOP_MEMBER_REQUIRED_MILLIS = ROOM_TOP_MEMBER_REQUIRED_HOURS * MILLIS_PER_HOUR
    const val ROOM_MAX_XP = ROOM_MAX_LEVEL * ROOM_XP_PER_LEVEL
}
